export const metadata = {
    title: "Cart",
    description: "Generated by create next app",
};

export default function CartLayout({ children }) {
    return (
        <div className="min-h-full flex flex-col">
            {children}
        </div>
    );
}
