import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./Components/AppSidebar";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Shopify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex">
        <SidebarProvider>
          <div className="flex flex-col flex-1">
            <header className="border-b px-4 py-3 flex items-center justify-between w-full">
              <div className="flex items-center gap-3">
                <SidebarTrigger className={"text-blue-600 hover:text-blue-800"}/>
                <Link href="/" className="font-bold text-blue-600 text-lg">Shopify</Link>
              </div>
            </header>

            <div className="flex flex-1">
              <AppSidebar />
              <main className="flex-1 p-4">{children}</main>
            </div>

          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}