export const metadata = {
  title: "Sign up",
  description: "Generated by create next app",
};

export default function SignupLayout({ children }) {
  return (
    <div className="min-h-full flex flex-col">
      {children}
    </div>
  );
}
